version: '3'

services:
    go-test-app:
        build: .
        ports:
            - '9000:9000'
        # docker environment variable
        environment:               
            - MONGOURI=mongodb://mongo:27017

    mongo:
        image: "mongo"
        ports:
            - '27017:27017'
        volumes:
            - "mongodb:/data/db"
        
    
volumes:
    mongodb:
        driver: local
        # command: bash -c "nodemon server.js"
